language: rust
cache: cargo

rust:
  - nightly

os:
  - linux
  - osx

before_script:
  - rustup toolchain install nightly-2020-05-15
  - rustup default nightly-2020-05-15
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- --deny warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
