[package]
name = "minitrace"
version = "0.0.1"
authors = ["zhongzc <zhongzc_arch@outlook.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
pin-project = "0.4"
minitrace-attribute = { path = "./attribute" }

[dependencies.futures_01]
version = "0.1"
package = "futures"

[dependencies.futures_03]
version = "0.3.1"
package = "futures"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
criterion = "0.3"

[[bench]]
name = "benches"
harness = false